# language: vi 
# pipeline:
#   - name: "WhitespaceTokenizer"
#   - name: "RegexFeaturizer"
#   - name: "LexicalSyntacticFeaturizer"
#   - name: "CountVectorsFeaturizer"
#   - name: "DIETClassifier"
#     epochs: 100

# language: "vi"

# pipeline:
#   # - name: "rasa_config.underthesea_tokenizer.UndertheseaTokenizer"  # Path to your custom tokenizer
#   - name: "underthesea_tokenizer"
#     class: "under_tokenizer2.UndertheseaTokenizer"

#   - name: "WhitespaceTokenizer"
#   - name: "RegexFeaturizer"
#   - name: "LexicalSyntacticFeaturizer"
#   - name: "CountVectorsFeaturizer"
#     analyzer: "char_wb"
#     min_ngram: 1
#     max_ngram: 4 # use character-level n-grams for Vietnamese
#   - name: "DIETClassifier"
#     entity_recognition: true
#     epochs: 100

language: "vi"

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "DIETClassifier"
    epochs: 100
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100
  - name: "LanguageModelFeaturizer"
    model_name: "bert"
    model_weights: "rasa/LaBSE"